### ISSUE TITLE
docs(whitepaper-arch-diag)

### ISSUE THREAD

**Issue by sfuji822** [hyperledger/cacti#1306] opened 2021-09-07 05:00 UTC
**Describe the bug**

The architectural diagram in the whitepaper is inconsistent with current codes, and it should be updated.

**Comment by petermetz** [comment] 2021-09-13 20:17
@sfuji822 Which section/page is it in?
I recommend also putting a little more info in the title of the issue, right now it just identifies that the issue is about a diagram in the whitepaper but it doesn't say anything about what the change is about that will be applied.

**Comment by outSH** [comment] 2023-12-19 10:38
Closing since the whitepaper requires complete update (https://github.com/hyperledger/cacti/issues/2165)

**Closed by outSH** 2023-12-19 10:38 UTC
Labels: bug
