### ISSUE TITLE
docs(examples): fix supply chain example - Deployment of smart contracts crashed:  Error: Invalid JSON RPC response: ""

### ISSUE THREAD

**Issue by sichen1234** [hyperledger/cacti#1063] opened 2021-06-18 15:38 UTC
**Describe the bug**

Trying to run the supply chain example gives the error
Deployment of smart contracts crashed:  Error: Invalid JSON RPC response: ""

This screenshot shows the error message from the log file in Docker:
![Screen Shot 2021-06-18 at 8 34 22 AM](https://user-images.githubusercontent.com/1706353/122585661-969f2b80-d010-11eb-82ec-694be5743a3b.png)

This is how I ran it:
[supplychain.log](https://github.com/hyperledger/cactus/files/6678040/supplychain.log)

I'm on OS X 11.2.3

**Comment by sichen1234** [comment] 2021-06-18 16:51
Tried this from a new checkout from hyperledger/cactus and after an hour, it's still stuck on Starting dummy infrastructure...
![Screen Shot 2021-06-18 at 9 50 13 AM](https://user-images.githubusercontent.com/1706353/122593579-b89dab80-d01a-11eb-9f4f-f935f9752993.png)

**Comment by petermetz** [comment] 2021-06-18 19:34
@sichen1234 An hour is where I'd say it's probably not going to start up (usually takes around 10 minutes on my machine with a very good internet connection)

Just to clarify, is this the docker image that you have built locally or the "official" one pulled directly from DockerHub?

**Comment by sichen1234** [comment] 2021-06-18 21:02
I deleted the local image and pulled a new one -- see these screenshots, and it's been about an hour, and still nothing is happening.
![Screen Shot 2021-06-18 at 2 01 17 PM](https://user-images.githubusercontent.com/1706353/122615688-c57fc680-d03d-11eb-8daa-873a705f3157.png)
![Screen Shot 2021-06-18 at 2 01 27 PM](https://user-images.githubusercontent.com/1706353/122615693-c7e22080-d03d-11eb-9f75-04ee9122b56f.png)

**Comment by petermetz** [comment] 2021-06-23 03:28
@sichen1234 Opened a PR with the supposed fix, please hold on while it gets green-lit + merged..

**Comment by sichen1234** [comment] 2021-06-28 18:16
Hi @petermetz I now get a different error:
SupplyChainApp crashed. Existing... CodedError: "goGetRes.code === null" is falsy, need a truthy value.

![Screen Shot 2021-06-28 at 11 11 18 AM](https://user-images.githubusercontent.com/1706353/123684372-3a9f8880-d802-11eb-8fc9-208356a669b0.png)
![Screen Shot 2021-06-28 at 11 11 41 AM](https://user-images.githubusercontent.com/1706353/123684384-3d9a7900-d802-11eb-8987-3a2be11505fb.png)
![Screen Shot 2021-06-28 at 11 11 50 AM](https://user-images.githubusercontent.com/1706353/123684393-3ffcd300-d802-11eb-9780-7337b98c4054.png)
![Screen Shot 2021-06-28 at 11 11 59 AM](https://user-images.githubusercontent.com/1706353/123684406-43905a00-d802-11eb-8b2c-bab14a2fd27b.png)
![Screen Shot 2021-06-28 at 11 13 21 AM](https://user-images.githubusercontent.com/1706353/123684412-45f2b400-d802-11eb-93e3-9e228511c0cf.png)

**Comment by petermetz** [comment] 2021-06-29 22:56
@sichen1234 Oops, apologies, I'm working on a fix (a second try) as we speak. Will keep you posted!

**Comment by petermetz** [comment] 2021-07-02 02:19
@sichen1234 I've submitted (yet) another fix, I'm more confident in it this time. Could you please give it another try? (sorry for messing up the previous fix)

It will take some time for the pull request to get merged, but even in the meantime you could test it out by running the same docker run command but with the *new* image specified at the end like this:

```sh
docker run \
      --rm \
      --privileged \
      -p 3000:3000 \
      -p 3100:3100 \
      -p 3200:3200 \
      -p 4000:4000 \
      -p 4100:4100 \
      -p 4200:4200 \
      ghcr.io/hyperledger/cactus-example-supply-chain-app:2021-07-01--fix-1063-v2
```

**Comment by sichen1234** [comment] 2021-07-03 01:23
Hi @petermetz I tried it again.  It's a lot better!  But I didn't get to Cactus Cockpit reachable http://0.0.0.0:3100

There is still a
`[2021-07-03T01:07:32.169Z] ERROR (SupplyChainAppDummyInfrastructure): Deployment of smart contracts crashed:  CodedError: "goGetRes.code === null" is falsy, need a truthy value.
[Cactus log 20210702.zip](https://github.com/hyperledger/cactus/files/6757663/Cactus.log.20210702.zip)
`

**Comment by sichen1234** [comment] 2021-07-03 01:24
Here is the log file: [Cactus log 20210702.zip](https://github.com/hyperledger/cactus/files/6757664/Cactus.log.20210702.zip)

**Comment by petermetz** [comment] 2021-07-03 01:41
Hi @sichen1234 thank you for testing it again! Could you confirm the amount of RAM you have in the computer that you ran the container on? Exit code `137` means (usually) that Linux has run out of memory so.

**Comment by sichen1234** [comment] 2021-07-05 18:33
I was running it on a Mac with 16 GB of RAM
-----
Si Chen
Open Source Strategies, Inc.

New Video: Creating Climate Solutions with Blockchain and Open Source
<https://youtu.be/gtO3COq8crQ>

**Comment by petermetz** [comment] 2021-07-07 22:08
> I was running it on a Mac with 16 GB of RAM 

@sichen1234 Hm, okay, then one last thing: Could you please try again, just to filter out the possibility of a fluke? (Unfortunately it happens sometimes that the network cuts out when dependencies are being downloaded, things like that). It's either a fluke or a race condition somewhere that doesn't reproduce on my machine so want to make sure we narrow it down as much as possible, apologies. :-)

**Comment by arun-rj** [comment] 2021-07-08 03:32
I was facing the same problem 
"goGetRes.code === null" is falsy, need a truthy value
The fix solved my problem. Thank you. Running it on an Ubuntu VM with 8GB RAM btw.

**Comment by petermetz** [comment] 2021-07-08 03:54
@arun-rj Awesome, thank you very much for giving it a go as well, good to have more data points for debugging!

**Comment by sichen1234** [comment] 2021-08-10 23:45
I just got around to trying it again and am still getting the error
`
[2021-08-10T23:43:24.535Z] ERROR (SupplyChainAppDummyInfrastructure): Deployment of smart contracts crashed:  CodedError: "goGetRes.code === null" is falsy, need a truthy value.
`

Is the fix already in the main branch or did I need to do anything else to get it to work correctly?

**Comment by petermetz** [comment] 2021-08-12 18:13
@sichen1234 

> Is the fix already in the main branch or did I need to do anything else to get it to work correctly?

It is on main, you shouldn't need to do anything else, because everything is inside the container image anyway (you don't even need to have the cactus repo checked out to run that docker container at all - it's designed to be as self contained as possible).

> I just got around to trying it again and am still getting the error
[2021-08-10T23:43:24.535Z] ERROR (SupplyChainAppDummyInfrastructure): Deployment of smart contracts crashed: CodedError: "goGetRes.code === null" is falsy, need a truthy value.

That's a tough one, I'm pretty sure you are still being hit by the flake that the fabric-samples repo does sometimes (the supply chain example uses that under the hood to run a fabric ledger).
I'll try to investigate further how we could improve the situation there because it's very unfortunate that for some it "just works" and for other's it's the exact opposite. Sorry about the bad experience! For now, the best idea I have is that if you have access to another computer, try running it there (a cloud instance can also work).
In the near future I have hopes that we'll be able to publish a public test instance where the supply chain app would be up and running for everyone to see/give it a go, but we are not there just yet.

**Comment by sichen1234** [comment] 2021-08-12 19:07
OK, I tried it on another Ubuntu instance and it worked :)

-----
Si Chen
Open Source Strategies, Inc.

New Video: Creating Climate Solutions with Blockchain and Open Source
<https://youtu.be/gtO3COq8crQ>

**Comment by petermetz** [comment] 2021-08-12 22:28
@sichen1234 YES! Very glad to hear that! I'll keep this issue open because it should work on every machine the same way, thank you for checking on it again, I appreciate the time you put into it!

**Comment by outSH** [comment] 2023-12-19 10:00
No new reports with that problem and containers has been updated since then, closing for now

**Closed by outSH** 2023-12-19 10:00 UTC
Labels: bug, documentation
