### ISSUE TITLE
quick question about running example of CBDC

### ISSUE THREAD

**Issue by onionhon** [hyperledger/cacti#2759] opened 2023-10-10 20:34 UTC
I have the problem that I have all the images running for the "CBDC" example which are "farbric all in one", "Besu all in one", "IPFS" and "front-end". But the front end page shows the "api-server" was not connected. I wonder what else I need to do other than running all the images?

**Comment by petermetz** [comment] 2023-10-12 22:21
@onionhon Sorry but without the list of exact steps/commands you took/ran, it's impossible to say what could be going wrong. When I follow the steps in the docs, it "just works" so try to look at where you diverted from those steps by any chance.

**Comment by petermetz** [comment] 2023-10-19 01:29
> > @onionhon Sorry but without the list of exact steps/commands you took/ran, it's impossible to say what could be going wrong. When I follow the steps in the docs, it "just works" so try to look at where you diverted from those steps by any chance.
> 
> Hi, I set up all the dependicies, and sucessfully run "npm run configure", but when i try to run the app. there's an error
> 
> "ubuntu@ip-172-31-23-247:~/cacti$ npm run start:example-cbdc-bridging-app
> 
> > start:example-cbdc-bridging-app
> > node -r ts-node/register examples/cactus-example-cbdc-bridging-backend/dist/lib/main/typescript/cbdc-bridging-app-cli.js dotenv_config_path=examples/cactus-example-cbdc-bridging-backend/process.env
> 
> Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/ubuntu/cacti/node_modules/ipfs-http-client/package.json at new NodeError (node:internal/errors:371:5) at throwExportsNotFound (node:internal/modules/esm/resolve:453:9) at packageExportsResolve (node:internal/modules/esm/resolve:671:7) at resolveExports (node:internal/modules/cjs/loader:482:36) at Function.Module._findPath (node:internal/modules/cjs/loader:522:31) at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27) at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/ubuntu/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30) at Function.Module._load (node:internal/modules/cjs/loader:778:27) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) { code: 'ERR_PACKAGE_PATH_NOT_EXPORTED' } "

@hongxiangz That one is a more recent bug that was created yesterday so it couldn't have been the original root cause.
We'll fix this but then once it's ready please re-do the steps and verify.

**Comment by outSH** [comment] 2023-12-29 11:39
Should be working now, @hongxiangz please retest and let us know if this can be closed

**Comment by hongxiangz** [comment] 2023-12-29 23:15
I am good now. Please close this one, thanks for working on that.

Michal Bajer ***@***.***> 于2023年12月29日周五 06:39写道：

**Closed** 2023-12-29 23:42 UTC
Labels: documentation, question
