### ISSUE TITLE
Bug docker exit and connection error macOS

### ISSUE THREAD

**Issue by vishk23** [hyperledger/cacti#2314] opened 2023-03-12 03:37 UTC
I am trying the docker command listed on the supply chain demo, I run it and I keep getting this error, I am unable to proceed. 

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-03-12 02:37:49,264 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-03-12 02:37:49,364 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2023-03-12 02:37:49,365 INFO supervisord started with pid 1
2023-03-12 02:37:50,372 INFO spawned: 'dockerd' with pid 20
2023-03-12 02:37:50,381 INFO spawned: 'supply-chain-app' with pid 22
2023-03-12 02:37:52,077 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:37:52,078 INFO success: supply-chain-app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:37:53,554 INFO exited: dockerd (exit status 1; not expected)
2023-03-12 02:37:54,563 INFO spawned: 'dockerd' with pid 168
2023-03-12 02:37:55,919 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Keccak bindings are not compiled. Pure JS implementation will be used.
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
2023-03-12 02:37:57,437 INFO exited: dockerd (exit status 1; not expected)
2023-03-12 02:37:58,443 INFO spawned: 'dockerd' with pid 306
2023-03-12 02:38:00,015 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:01,034 INFO exited: dockerd (exit status 1; not expected)
2023-03-12 02:38:02,039 INFO spawned: 'dockerd' with pid 436
2023-03-12 02:38:03,494 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:04,508 INFO exited: dockerd (exit status 1; not expected)
[2023-03-12T02:38:04.798Z] INFO (config-service): Configuration validation OK.
2023-03-12 02:38:04,809 INFO spawned: 'dockerd' with pid 557
[2023-03-12T02:38:04.807Z] INFO (supply-chain-app): Instantiating new keychain plugin...
[2023-03-12T02:38:04.830Z] INFO (PluginKeychainMemory): Created PluginKeychainMemory. KeychainID=fabb9e76-7fd7-4849-9695-e3b5a9b45cae
[2023-03-12T02:38:04.830Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
[2023-03-12T02:38:04.831Z] INFO (supply-chain-app): KeychainID='fabb9e76-7fd7-4849-9695-e3b5a9b45cae'
[2023-03-12T02:38:04.853Z] INFO (SupplyChainAppDummyInfrastructure): Reusing the provided keychain plugin...
[2023-03-12T02:38:04.853Z] INFO (SupplyChainAppDummyInfrastructure): KeychainID='fabb9e76-7fd7-4849-9695-e3b5a9b45cae'
[2023-03-12T02:38:04.856Z] DEBUG (supply-chain-app): Starting SupplyChainApp...
[2023-03-12T02:38:04.859Z] DEBUG (supply-chain-app): Registered signal handlers for graceful auto-shutdown
[2023-03-12T02:38:04.860Z] INFO (SupplyChainAppDummyInfrastructure): Starting dummy infrastructure...
[2023-03-12T02:38:04.931Z] ERROR (containers#tryPullImage()): Could not even start ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2 pull: Error: connect ECONNREFUSED /var/run/docker.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/var/run/docker.sock'
}
2023-03-12 02:38:06,132 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:07,184 INFO exited: dockerd (exit status 1; not expected)
[2023-03-12T02:38:07.191Z] ERROR (containers#tryPullImage()): Could not even start ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2 pull: Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-03-12 02:38:07,198 INFO spawned: 'dockerd' with pid 684
2023-03-12 02:38:08,443 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:09,464 INFO exited: dockerd (exit status 1; not expected)
[2023-03-12T02:38:09.464Z] ERROR (containers#tryPullImage()): Could not even start ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2 pull: Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-03-12 02:38:09,468 INFO spawned: 'dockerd' with pid 807
2023-03-12 02:38:10,858 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:13,739 INFO exited: dockerd (exit status 1; not expected)
[2023-03-12T02:38:13.740Z] ERROR (containers#tryPullImage()): Could not even start ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2 pull: Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-03-12 02:38:13,745 INFO spawned: 'dockerd' with pid 940
2023-03-12 02:38:14,919 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:15,934 INFO exited: dockerd (exit status 1; not expected)
2023-03-12 02:38:16,939 INFO spawned: 'dockerd' with pid 1072
2023-03-12 02:38:18,261 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:19,285 INFO exited: dockerd (exit status 1; not expected)
2023-03-12 02:38:20,293 INFO spawned: 'dockerd' with pid 1202
2023-03-12 02:38:21,518 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:22,537 INFO exited: dockerd (exit status 1; not expected)
[2023-03-12T02:38:22.539Z] ERROR (containers#tryPullImage()): Could not even start ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2 pull: Error: read ECONNRESET
    at Pipe.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
2023-03-12 02:38:22,543 INFO spawned: 'dockerd' with pid 1323
2023-03-12 02:38:23,716 INFO success: dockerd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-12 02:38:24,731 INFO exited: dockerd (exit status 1; not expected)`

errors continue in a loop like this

I cannot figure out what to do please help.

macOS 13.1
M1 Pro

**Comment by jagpreetsinghsasan** [comment] 2023-03-14 05:20
This works on my Ubuntu 20.04 system. Can't be sure about M1 based systems.
Can anyone else look into this who has a similar working environment?

**Comment by jagpreetsinghsasan** [comment] 2023-03-14 05:22
In the meanwhile, somone responds, @vishk23 can you please attach the entire log as a file instead? (It will be easier to check)

**Comment by vishk23** [comment] 2023-03-14 15:47
[dockerlogs.txt](https://github.com/hyperledger/cacti/files/10970658/dockerlogs.txt)

**Comment by petermetz** [comment] 2023-03-21 01:34
@vishk23 The logs show that the image pull itself is already not working on your machine so it's possible that the issue is not related to the M1 (though that's the most likely culprit).

Please check what happens if you do a `docker pull ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2` because it says in the logs you attached that it fails at the pull. Please include the complete log output in a text file for the docker pull command in your reply as well.

```sh
2023-03-14 08:29:39 [2023-03-14T12:29:39.435Z] ERROR (containers#tryPullImage()): Could not even start ghcr.io/hyperledger/cactus-fabric-all-in-one:v1.0.0-rc.2 pull: Error: read ECONNRESET
\
2023-03-14 08:29:39     at Pipe.onStreamRead (node:internal/stream_base_commons:220:20) \{
```

**Comment by petermetz** [comment] 2023-03-28 20:07
@vishk23 If you see the problem again please re-open the issue. Closing in the meantime just to try and keep a tidy(er) list of tasks.

**Closed by petermetz** 2023-03-28 20:07 UTC
Labels: bug, wontfix
