### ISSUE TITLE
test(connector-go-ethereum-socketio): add Jest tests

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2106] opened 2022-06-30 20:34 UTC
### Description

Add Jest compatible unit and integration tests to the package under the path:
`packages/cactus-plugin-ledger-connector-go-ethereum-socketio/src/test/typescript/...`

### Acceptance Criteria
1. ci.yml also updated to execute these tests as part of the CI

cc: @takeutak @outSH @izuru0

**Comment by outSH** [comment] 2022-07-01 08:25
@petermetz This is a duplicate of https://github.com/hyperledger/cactus/issues/2052, can be closed.

**Closed** 2023-12-29 11:15 UTC
Labels: Tests, Jestify
