### ISSUE TITLE
HTLC Coordinator

### ISSUE THREAD

**Issue by jordigiam** [hyperledger/cacti#869] opened 2021-04-26 15:49 UTC
**Is your feature request related to a problem? Please describe.**
As a user I want to exchange funds between different blockchain networks using HTLCs contracts.

**Describe the solution you'd like**
Generate a new plugin called HTLC Coordinator that can be used as a plugin to make an exchange. The plugin will use the HTLC plugins and will have an interface to interact with them. 
The following functions are required:
- **newCoordinator()**  Function that given the information about the htlc plugin to be used, creates an instance of the plugin, deploy the contract and returns an instance of the coordinator and keep listening the events.
- **newCounterparty()**  Function that given the information about the htlc plugin to connect to the counterparty network and contract creates an instance of the plugin, and check that contract exists.
- **withdrawCounterparty()** Function that withdraw the funds of the counterparty contract.

The coordinator instance need catch the events emitted by the contract to know when can withdraw the funds.

**Additional context**
<img width="1048" alt="Captura de pantalla 2021-04-14 a las 16 53 21" src="https://user-images.githubusercontent.com/78140052/116108644-642e1d80-a6b4-11eb-8a03-6c525d4ce8c3.png">
<img width="1062" alt="Captura de pantalla 2021-04-14 a las 16 52 29" src="https://user-images.githubusercontent.com/78140052/116108654-65f7e100-a6b4-11eb-8b35-39d634278a35.png">

**Comment by jordigiam** [comment] 2021-04-28 15:57
It's necessary update the HTLC's PR's to use the new version of the connectors plugins

**Comment by petermetz** [comment] 2021-04-28 17:34
@jordigiam @AzaharaC Please 
1. Rebase your respective HTLC PRs to latest main
2. Put the compiler appeasing hack back in for the plugin aspect enum (substitute with string constant + casting)
3. Make sure the tests are passing
4. Remove the dependency on https://github.com/hyperledger/cactus/issues/586 (by editing the PR description)
5. Merge the PRs with the enum workaround.

**Comment by outSH** [comment] 2023-12-15 11:25
Duplicate of #953 and already solved, closing

**Closed by outSH** 2023-12-15 11:25 UTC
Labels: enhancement, Epic, P3
