### ISSUE TITLE
test(ci): fix flake AMQ214015 Failed to execute connection life cycle

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2378] opened 2023-04-07 02:24 UTC
**Describe the bug**

The `.github/workflows/test_weaver-data-sharing.yml` CI job occasionally fails (e.g. flaky test)

Not sure at all if this AMQ error code is actually the root cause or just some inconsequential error log, but at the end of the job log it says so something is definitely up.

```sh
2023-04-07T00:55:43.0880902Z Passed 10/12 Tests.
2023-04-07T00:55:43.0885113Z ##[error]Process completed with exit code 1.

```

**To Reproduce**

Run the CI until it fails randomly. Eventually it will.

**Expected behavior**

Test is consistently succeeding in all the different environments.

**Logs/Stack traces**

[2023-04-07T00-31-21-weaver-data-sharing-local-crash-ci.log](https://github.com/hyperledger/cacti/files/11175609/2023-04-07T00-31-21-weaver-data-sharing-local-crash-ci.log)

**Cloud provider or hardware configuration:**

GitHub/BuildJet

**Operating system name, version, build:**

Ubuntu-20.04

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main`

cc: @VRamakrishna @sandeepnRES

**Comment by sandeepnRES** [comment] 2023-06-19 09:27
Just to correct, AMQ error code isn't the cause, that step is still passing as per logs.
Error was: `2023-04-07T00:54:54.5670941Z 2023-04-07 00:54:54 [31merror[39m [fabric-cli]: Error verifying and storing state: Error: InteropFlow remote view request error: Error: InteropFlow relay response error: Error: Error: State error: Error: Timeout: State is still pending.`
Timeout error, which I think is resolved with PR #2438 , which increases the timeout value.

**Closed by sandeepnRES** 2023-06-19 09:27 UTC
Labels: bug, Flaky-Test-Automation, Tests, Weaver
