### ISSUE TITLE
docs(examples/cbdc): fix successful minting on chaincode results in balance 0

### ISSUE THREAD

**Issue by Anusha-Padmanabhan** [hyperledger/cacti#2739] opened 2023-10-04 09:52 UTC
**Describe the bug**

Started the app of CBDC example and front end using the commands as per the given readme.
https://github.com/hyperledger/cacti/tree/main/examples/cactus-example-cbdc-bridging-backend
I am getting the below UI,

<img width="919" alt="cdbc_output" src="https://github.com/hyperledger/cacti/assets/119853495/09b43fc3-fa2a-4fa6-b9e8-69e266125386">

 I can able to mint and see the transaction logs but after minting where I can view those tokens and what is the next step to do transfer, escrow, bridge out and in.

**To Reproduce**

clone the repository
cd cactus
from the root of the repository run the below commands:
npm run enable-corepack
npm run configure
npm run start:example-cbdc-bridging-app

**Expected behavior**

Minted token should reflect somewhere or enable the other buttons of transfer, escrow
Steps to understand the workflow of CBDC example is missing

**Logs/Stack traces**

Can help maintainers identify root causes

**Screenshots**

**`docker run -p 2000:2000 aaugusto11/cactus-example-cbdc-bridging-frontend`**

<img width="587" alt="CDBC_frontend_2" src="https://github.com/hyperledger/cacti/assets/119853495/bd6b19e4-91fc-476d-ab42-76645d6736b7">

**`npm run start:example-cbdc-bridging-app`**

<img width="848" alt="CBDC_backend" src="https://github.com/hyperledger/cacti/assets/119853495/7109c205-9a7b-4c5b-bc53-ba1938e25299">

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

Either a semantic version of the release you are using such as `1.0.0` or a git
commit hash if you are directly working with code from the git repository.

**Hyperledger Cactus Plugins/Connectors Used**

 - Which DLT connectors are you using (Fabric, Quorum, Corda, Besu, etc.)

**Additional context**

**Comment by petermetz** [comment] 2023-10-04 17:47
@Anusha-Padmanabhan I'll try to answer, but @RafaelAPB and @AndreAugusto11 might have a more up to date picture on this.

> I can able to mint and see the transaction logs but after minting where I can view those tokens 

If you've set up the example as per the steps, then the ledgers are running on your machine, so you could observe the ledger state by querying those containers in your preferred way.

> and what is the next step to do transfer, escrow, bridge out and in.

If I remember correctly you unlock those options on the UI by putting the tokes into escrow first. Let me know if this helps, in the meantime I'm closing the question as answered, but of course feel free to re-open as needed.

**Comment by Anusha-Padmanabhan** [comment] 2023-10-05 07:02
@petermetz  Thanks for the response, But the escrow button is not enabled after minting and token balance is also not reflecting in the screen.
Attaching the screenshot  after minting.
<img width="366" alt="token_reflection" src="https://github.com/hyperledger/cacti/assets/119853495/56005139-a810-4050-99e9-48ce50c4cf26">

I believe, once after minting escrow and transfer buttons should get enabled and minted token balance also should be visible in the screen.

**Comment by petermetz** [comment] 2023-10-05 21:24
@Anusha-Padmanabhan I went ahead and re-did the steps as well, it won't re-enable. 
The minting seems to succeed but then as the UI calls the balanceOf method of the contract, that returns 0 after the successful minting anyway. Looks like this got broken somewhere along the way so I'm re-opening this as a bug.

cc: @RafaelAPB @AndreAugusto11

**Comment by AndreAugusto11** [comment] 2023-10-05 21:32
Hi @petermetz and @Anusha-Padmanabhan thank you for your feedback. I will have a look at this asap, and ping you here

**Comment by petermetz** [comment] 2023-10-05 21:35
> Hi @petermetz and @Anusha-Padmanabhan thank you for your feedback. I will have a look at this asap, and ping you here

@AndreAugusto11 Nice, thank you very much for helping!!!

**Comment by AndreAugusto11** [comment] 2023-10-06 10:58
@petermetz this is definitely a strange one. I checked the chaincode container logs, and the tokens are being minted correctly. So, the problem is in the GET request, which is always returning 0. I haven't changed anything in the code, have there been any breaking changes that might be causing this (also in the Fabric all in one image)?

**Comment by petermetz** [comment] 2023-10-14 07:01
> @petermetz this is definitely a strange one. I checked the chaincode container logs, and the tokens are being minted correctly. So, the problem is in the GET request, which is always returning 0. I haven't changed anything in the code, have there been any breaking changes that might be causing this (also in the Fabric all in one image)?

@AndreAugusto11 I also checked the chaincode container logs and the computed state keys are inconsistent so something is off with the minting configuration IMO.
If you log the keys in the contract then you'll see that the Mint and the BalanceOf methods generate different state keys such as shown below (observe the first 2 components being swapped)
They are technically identical identities, but the contract uses plain strings for the state keys so they end up being different anyway and that's why the BalanceOf can't find the tokens of the identity that were minted.

```sh
x509::/OU=org1/OU=client/OU=department1/CN=userA::/C=US/ST=North Carolina/L=Durham/O=org1.example.com/CN=ca.org1.example.com
x509::/OU=client/OU=org1/OU=department1/CN=userA::/C=US/ST=North Carolina/L=Durham/O=org1.example.com/CN=ca.org1.example.com
```

**Comment by AndreAugusto11** [comment] 2023-10-17 20:01
@petermetz thanks for providing those logs.

So, the Mint function calculates the clientID dynamically based on the request, and the BalanceOf function receives as an argument the clientID provided by the front end. For some reason, those identities got mismatched. I have updated the code such that the Mint function receives the identity just like the Balance function does.

I haven't tested because I'm having some issues with my GCP VM (can't do it in my M1), can you do it @Anusha-Padmanabhan?

**Comment by Anusha-Padmanabhan** [comment] 2023-10-18 04:19
Sure @AndreAugusto11, I will test and let you know..

**Closed** 2023-10-18 04:43 UTC
Labels: bug, documentation, question, Developer_Experience, P2

**Comment by Anusha-Padmanabhan** [comment] 2023-10-19 14:34
Hi @petermetz  @AndreAugusto11 
Could you please share the node and npm version you have used to test the cbdc app, Since I am getting the following error once after starting the app using the command "npm run start:example-cbdc-bridging-app".

<img width="954" alt="Error_path_not found" src="https://github.com/hyperledger/cacti/assets/119853495/e2f94736-6447-4631-9bf8-da60416f9225">
